package top.jf.dal.entity;

public class UserTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.id
     *
     * @mbg.generated Fri Jul 07 09:52:36 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.username
     *
     * @mbg.generated Fri Jul 07 09:52:36 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.password
     *
     * @mbg.generated Fri Jul 07 09:52:36 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.sex
     *
     * @mbg.generated Fri Jul 07 09:52:36 CST 2017
     */
    private Integer sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.id
     *
     * @return the value of user_test.id
     *
     * @mbg.generated Fri Jul 07 09:52:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.id
     *
     * @param id the value for user_test.id
     *
     * @mbg.generated Fri Jul 07 09:52:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.username
     *
     * @return the value of user_test.username
     *
     * @mbg.generated Fri Jul 07 09:52:36 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.username
     *
     * @param username the value for user_test.username
     *
     * @mbg.generated Fri Jul 07 09:52:36 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.password
     *
     * @return the value of user_test.password
     *
     * @mbg.generated Fri Jul 07 09:52:36 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.password
     *
     * @param password the value for user_test.password
     *
     * @mbg.generated Fri Jul 07 09:52:36 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.sex
     *
     * @return the value of user_test.sex
     *
     * @mbg.generated Fri Jul 07 09:52:36 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.sex
     *
     * @param sex the value for user_test.sex
     *
     * @mbg.generated Fri Jul 07 09:52:36 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }
}